theme: jekyll-theme-cayman
url: "ijayasurya.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - amp-jekyll
  - jekyll-feed
title: Jayasurya Mayilsamy
description: Do you know who am i?
author: Jayasurya Mayilsamy
